# Generated by Django 4.1.5 on 2023-01-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('img_url', models.CharField(help_text='the url to the image displayed in the about section', max_length=256)),
                ('order', models.SmallIntegerField(unique=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'about_section',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content_html', models.TextField()),
            ],
            options={
                'db_table': 'footer',
            },
        ),
    ]
