# Generated by Django 4.1.5 on 2023-01-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
