# Generated by Django 4.1.5 on 2023-01-14 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tag',
            table='tag',
        ),
    ]
